<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateKintaisTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('kintais', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id');
            $table->string('date');
            $table->time('work_start_01')->nullable(true);;
            $table->time('work_start_02')->nullable(true);;
            $table->time('work_start_03')->nullable(true);;
            $table->time('work_start_04')->nullable(true);;
            $table->time('work_start_05')->nullable(true);;
            $table->time('work_start_06')->nullable(true);;
            $table->time('work_start_07')->nullable(true);;
            $table->time('work_start_08')->nullable(true);;
            $table->time('work_start_09')->nullable(true);;
            $table->time('work_start_10')->nullable(true);;
            $table->time('work_start_11')->nullable(true);;
            $table->time('work_start_12')->nullable(true);;
            $table->time('work_start_13')->nullable(true);;
            $table->time('work_start_14')->nullable(true);;
            $table->time('work_start_15')->nullable(true);;
            $table->time('work_start_16')->nullable(true);;
            $table->time('work_start_17')->nullable(true);;
            $table->time('work_start_18')->nullable(true);;
            $table->time('work_start_19')->nullable(true);;
            $table->time('work_start_20')->nullable(true);;
            $table->time('work_start_21')->nullable(true);;
            $table->time('work_start_22')->nullable(true);;
            $table->time('work_start_23')->nullable(true);;
            $table->time('work_start_24')->nullable(true);;
            $table->time('work_start_25')->nullable(true);;
            $table->time('work_start_26')->nullable(true);;
            $table->time('work_start_27')->nullable(true);;
            $table->time('work_start_28')->nullable(true);;
            $table->time('work_start_29')->nullable(true);;
            $table->time('work_start_30')->nullable(true);;
            $table->time('work_start_31')->nullable(true);;
            $table->time('work_end___01')->nullable(true);;
            $table->time('work_end___02')->nullable(true);;
            $table->time('work_end___03')->nullable(true);;
            $table->time('work_end___04')->nullable(true);;
            $table->time('work_end___05')->nullable(true);;
            $table->time('work_end___06')->nullable(true);;
            $table->time('work_end___07')->nullable(true);;
            $table->time('work_end___08')->nullable(true);;
            $table->time('work_end___09')->nullable(true);;
            $table->time('work_end___10')->nullable(true);;
            $table->time('work_end___11')->nullable(true);;
            $table->time('work_end___12')->nullable(true);;
            $table->time('work_end___13')->nullable(true);;
            $table->time('work_end___14')->nullable(true);;
            $table->time('work_end___15')->nullable(true);;
            $table->time('work_end___16')->nullable(true);;
            $table->time('work_end___17')->nullable(true);;
            $table->time('work_end___18')->nullable(true);;
            $table->time('work_end___19')->nullable(true);;
            $table->time('work_end___20')->nullable(true);;
            $table->time('work_end___21')->nullable(true);;
            $table->time('work_end___22')->nullable(true);;
            $table->time('work_end___23')->nullable(true);;
            $table->time('work_end___24')->nullable(true);;
            $table->time('work_end___25')->nullable(true);;
            $table->time('work_end___26')->nullable(true);;
            $table->time('work_end___27')->nullable(true);;
            $table->time('work_end___28')->nullable(true);;
            $table->time('work_end___29')->nullable(true);;
            $table->time('work_end___30')->nullable(true);;
            $table->time('work_end___31')->nullable(true);;
            $table->time('break_start01')->nullable(true);;
            $table->time('break_start02')->nullable(true);;
            $table->time('break_start03')->nullable(true);;
            $table->time('break_start04')->nullable(true);;
            $table->time('break_start05')->nullable(true);;
            $table->time('break_start06')->nullable(true);;
            $table->time('break_start07')->nullable(true);;
            $table->time('break_start08')->nullable(true);;
            $table->time('break_start09')->nullable(true);;
            $table->time('break_start10')->nullable(true);;
            $table->time('break_start11')->nullable(true);;
            $table->time('break_start12')->nullable(true);;
            $table->time('break_start13')->nullable(true);;
            $table->time('break_start14')->nullable(true);;
            $table->time('break_start15')->nullable(true);;
            $table->time('break_start16')->nullable(true);;
            $table->time('break_start17')->nullable(true);;
            $table->time('break_start18')->nullable(true);;
            $table->time('break_start19')->nullable(true);;
            $table->time('break_start20')->nullable(true);;
            $table->time('break_start21')->nullable(true);;
            $table->time('break_start22')->nullable(true);;
            $table->time('break_start23')->nullable(true);;
            $table->time('break_start24')->nullable(true);;
            $table->time('break_start25')->nullable(true);;
            $table->time('break_start26')->nullable(true);;
            $table->time('break_start27')->nullable(true);;
            $table->time('break_start28')->nullable(true);;
            $table->time('break_start29')->nullable(true);;
            $table->time('break_start30')->nullable(true);;
            $table->time('break_start31')->nullable(true);;
            $table->time('break_end__01')->nullable(true);;
            $table->time('break_end__02')->nullable(true);;
            $table->time('break_end__03')->nullable(true);;
            $table->time('break_end__04')->nullable(true);;
            $table->time('break_end__05')->nullable(true);;
            $table->time('break_end__06')->nullable(true);;
            $table->time('break_end__07')->nullable(true);;
            $table->time('break_end__08')->nullable(true);;
            $table->time('break_end__09')->nullable(true);;
            $table->time('break_end__10')->nullable(true);;
            $table->time('break_end__11')->nullable(true);;
            $table->time('break_end__12')->nullable(true);;
            $table->time('break_end__13')->nullable(true);;
            $table->time('break_end__14')->nullable(true);;
            $table->time('break_end__15')->nullable(true);;
            $table->time('break_end__16')->nullable(true);;
            $table->time('break_end__17')->nullable(true);;
            $table->time('break_end__18')->nullable(true);;
            $table->time('break_end__19')->nullable(true);;
            $table->time('break_end__20')->nullable(true);;
            $table->time('break_end__21')->nullable(true);;
            $table->time('break_end__22')->nullable(true);;
            $table->time('break_end__23')->nullable(true);;
            $table->time('break_end__24')->nullable(true);;
            $table->time('break_end__25')->nullable(true);;
            $table->time('break_end__26')->nullable(true);;
            $table->time('break_end__27')->nullable(true);;
            $table->time('break_end__28')->nullable(true);;
            $table->time('break_end__29')->nullable(true);;
            $table->time('break_end__30')->nullable(true);;
            $table->time('break_end__31')->nullable(true);;
            $table->timestamps();
            $table
                ->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('kintais');
    }
}
